package com.example.quizduellosu.ui.activities

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import com.example.quizduellosu.R // This will likely show an error until R is generated by a build

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        // setContentView(R.layout.activity_main) // Assuming activity_main.xml exists in res/layout
    }
}
